### ISSUE TITLE
WorldGuard Expansion not working with WorldGuard 7

### ISSUE THREAD

**Issue by AmazedMender16** [PlaceholderAPI/WorldGuard-Expansion#10]
### Issue
> What is the issue? Describe it like you would tell a friend.

The WorldGuard Expansion is not working with WorldGuard 7 

### Expected behaviour
> What should PlaceholderAPI do?

I would like it to work like with 1.12.2

### Actual behaviour
> What does PlaceholderAPI actually do?

Errors out when parsing the placeholder.
https://pastebin.com/qWCqLYtp

### How to reproduce
> What steps did you made, to get this bug?

Setup a server with the latest WorldGuard, WorldEdit, PlaceholderAPI, download the WorldGuard Expansion, reload Papi and parse on of the placeholders.

**Comment by aBo0oDyy** [comment]
This is due to WorldGuard API changes, there already an opened issue about that #8.
Glare has started working on it afaik, so please be patient.
If you have any additional information, please post in the issue mentioned above.
