### ISSUE TITLE
WorldGuard 1.14.4 Support

### ISSUE THREAD

**Issue by CarsonJF** [PlaceholderAPI/WorldGuard-Expansion#11]
### Issue
> What is the issue? Describe it like you would tell a friend.
When adding worldguard extension from ecloud, PAPI break completely. I realized that WG PAPI extension is only for 1.13, and would like it updated to 1.14.

### Expected behaviour
> What should PlaceholderAPI do?
for things such as /papi parse CarsonJF %worldguard_region_name% to parse back the region name.

### Actual behaviour
> What does PlaceholderAPI actually do?
after installing WG extension via /papi ecloud download WorldGuard, the entire breaks on reload/restart.

### How to reproduce
> What steps did you made, to get this bug?
1. run /papi ecloud download worldguard
2. run /papi reload or /restart on server

**Comment by aBo0oDyy** [comment]
Hey there,

Can you please provide more information please ?
Like the error you're getting when you restart/reload, and PAPI, WG and server versions ?

Open your issue in the correct place next time please.

**Comment by CarsonJF** [comment]
Error: https://pastebin.com/K0NmA7DV

WG 7.0.1-SNAPSHOT 

PAPI 2.10.3

Paper 152 1.14.4

**Comment by darbyjack** [comment]
I'm aware of it. We've just been busy. It's on our list of things to do.

**Comment by CarsonJF** [comment]
Understood. Just making sure its not lost and forgotten!

**Comment by darbyjack** [comment]
I'm having @aBo0oDyy push what I have so far to the ecloud. So 1.4.0 will be available soon. Just make sure to pay attention to the new placeholder list that will be in the new update.

**Comment by aBo0oDyy** [comment]
Expansion has been updated.
You can download it manually from [here](https://api.extendedclip.com/expansions/worldguard/), or run the following commands:
```
/papi ecloud refresh
/papi ecloud download WorldGuard
/papi reload
```
