### ISSUE TITLE
World Guard Problems With Region Display.

### ISSUE THREAD

**Issue by Prowco** [PlaceholderAPI/WorldGuard-Expansion#13]
### Issue
> What is the issue? Describe it like you would tell a friend.
I using the placeholder %worldguard_region_name% but if u are inside of a region with 2 or more regions inside with diferent prioritys the placeholders display the 3 regions very fast looks a liitle bug and ugly there its no way for display region by priority?

### How to reproduce
I just walk inside a region protected by more than 1 region for example: i create a region in all my city called well city xD then i make some another regions like apartments or stores or jobs so if u go inside a region for example acaciaapartments and u go inside this region the placeholder display acaciaapartments and city at the same time very fast so looks like bug and u cant read with clarity the region u are

**Comment by aBo0oDyy** [comment]
Hello,
I've fixed this in PR #14. Wait until it gets reviewed then I'll update it.
Or you can download it manually from [here](https://aboodyy.net/expansions/WorldGuard-Expansion-1.4.2.jar) and replace it with the old one in `plugins/PlaceholderAPI/expansions` folder.

With this version, placeholders will get the region that has the highest priority by default, or you can set it in the placeholder (`%worldguard_<Any WorldGuard Placeholder>_<Priority>%`).

Note: `<Priority>` is the region number, ordered by the region's priorities. So if you have 3 regions with priority 1, 10, 20, priority of `1` (`%worldguard_region_name_1%`) will use the highest priority region which is the region of priority `20`.

**Comment by Prowco** [comment]
ty

**Comment by Prowco** [comment]
Hi well i try install the new plugin and i put the new placeholder but dont work dont show the region at all xD 
https://i.imgur.com/6V3IKbT.png

**Comment by aBo0oDyy** [comment]
Is it working using the parse command? `/papi parse me %worldguard_region_name_1%`
If it is, then the issue is from the scoreboard plugin.
