### ISSUE TITLE
[Suggestion] Add Allow and Deny placeholder

### ISSUE THREAD

**Issue by Sinnethh** [PlaceholderAPI/WorldGuard-Expansion#17]
I'm not sure if this is possible but I think it'd be a great addon to have a placeholder being %worldguard_region_flag_flagname and have it return Allow or Deny and obviously "NULL" if the flag doesnt exist for the current region.

**Comment by aBooDyy** [comment]
Hello,
Thanks for your suggestion, I've added this placeholder but not sure if it will always work, don't know what would happen.
You can try it yourself and tell me if anything occurs.

The placeholder is `%worldguard_region_flag_<Flag name>%`
You can download it from [here](https://aboodyy.net/expansions/WorldGuard-Expansion-1.4.3.jar).

> How to install the new version?
> 
> - Download it from the link above.
> - Replace it with the current expansion jar you have in `plugins/PlaceholderAPI/expansions` folder.
> - Reload PlaceholderAPI `/papi reload`.
> - You're done!

**Comment by Szymanski09** [comment]
Hi, Download link doesn't work and I really need this for my minecraft server.

Could someone help me?
