### ISSUE TITLE
WorldGuard's placeholders throw errors. (Latest 1.13 Dev Version)

### ISSUE THREAD

**Issue by OverCrave** [PlaceholderAPI/WorldGuard-Expansion#2]
I would like to reference this issue I posted at enginehub: https://dev.enginehub.org/youtrack/issue/WORLDGUARD-3955

According to them, the issue lays with PlaceholderAPI itself.

**Comment by darbyjack** [comment]
Is there still errors? The WG has been updated since then.

**Comment by OverCrave** [comment]
Yes, it's the same issue. I tested on a newly installed server with only PlaceholderAPI, QuickBoard, WorldEdit and WorldGuard as plugins. Trying to use the placeholder for the name of the current region in QuickBoard'
s scoreboard results in QuickBoard not being able to reload and giving this error: https://hastebin.com/udanusuduz.md
(The only difference to the first report ist that this time QuickBoard was used instead of CMI for the scoreboard)

**Comment by OverCrave** [comment]
https://hastebin.com/ifitixodon.bash
Tried out all the WG placeholders with /papi parse, all of them getting the shown errors.

**Comment by aBo0oDyy** [comment]
Hey @OverCrave,

Can you please try the new version of the expansion ([v1.4.0](https://api.extendedclip.com/expansions/worldguard/versions/worldguard-140/)) and see of it fixes your issue?

Can't really tell since none of the link you've sent are working now.

**Comment by aBo0oDyy** [comment]
Closed duo to no reply from the author.
