### ISSUE TITLE
Placeholderapi Worldguard Expansion

### ISSUE THREAD

**Issue by Imortalshard** [PlaceholderAPI/WorldGuard-Expansion#8]
Hi,
When trying use placeholders from the worldguard papi expansion. I'm getting this error: https://pastebin.com/cggqzZzQ

I think placeholderapi needs a more updated expansion for worldguard. As both plugins are using the latest version. So it has to be the expansion itself. 

Thanks,
Imortalshard.

**Comment by aBo0oDyy** [comment]
Its because of the API changes in latest builds of WorldGuard, the expansion will hopefully be updated soon to support these changes.

**Comment by Imortalshard** [comment]
Any updates on when the expansion will be updated? Needing them for a few features on the servers i'm working on.

**Comment by darbyjack** [comment]
> Any updates on when the expansion will be updated? Needing them for a few features on the servers i'm working on.

I just added some more back in. Feel free to play with it.

**Comment by Imortalshard** [comment]
> > Any updates on when the expansion will be updated? Needing them for a few features on the servers i'm working on.
> 
> I just added some more back in. Feel free to play with it.

Am I needing to update the wordguard-expansion jar, or has it been updated on ecloud

**Comment by darbyjack** [comment]
Yes, just compile it and then try it.

**Comment by Imortalshard** [comment]
Never actually compiled anything before :P So not sure how

**Comment by darbyjack** [comment]
https://ci.extendedclip.com/job/WorldGuard-Expansion/6/artifact/target/WorldGuard-Expansion-1.4.0.jar

**Comment by Imortalshard** [comment]
I've tested it out and it works great, it has all the placeholders added i need but I am getting an error about one of them. 

`%worldguard_region_flags%`

http://prntscr.com/o8jmu9

**Comment by aBo0oDyy** [comment]
Hey @Imortalshard,

Thanks for reporting that, and sorry about the delay.
Issue has been fixed in [v1.4.1](https://api.extendedclip.com/expansions/worldguard/versions/worldguard-141/).
